name: Deploy to WordPress.org
on:
  push:
    branches:
    - test/github-action
jobs:
  gh-action:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        npm install
        npm run build
    - name: WordPress Plugin Deploy
      uses: dinhtungdu/action-wordpress-plugin-deploy@test
      with:
        generate-zip: true
